Reformat bash scripts

diff --git a/bin/dump b/bin/dump
--- a/bin/dump
+++ b/bin/dump
@@ -23,18 +23,21 @@ if source "${BASE_DIR}/.env" && source "${BASE_DIR}/docker/image/db/.env"; then
   fi
 
   DUMP_FILE="$(readlink --canonicalize "$(if [ "${2:0:1}" != / ]; then pwd; fi)/${2%.sql.gz}").sql.gz"
-  if [ -n "${*:3}" ]; then MYSQL_DATABASE="$3"; MYSQL_TABLES=("${@:4}"); fi
+  if [ -n "${*:3}" ]; then
+    MYSQL_DATABASE="$3"
+    MYSQL_TABLES=("${@:4}")
+  fi
 
   case "$1" in
-    -c|--create)
-      docker exec "${COMPOSE_PROJECT_NAME}-db" sh -c "exec mysqldump -u'${MYSQL_USER}' -p'${MYSQL_PASSWORD}' \
+  -c | --create)
+    docker exec "${COMPOSE_PROJECT_NAME}-db" sh -c "exec mysqldump -u'${MYSQL_USER}' -p'${MYSQL_PASSWORD}' \
         --single-transaction --quick --lock-tables --add-drop-table \
-        ${MYSQL_DATABASE} ${MYSQL_TABLES[*]} | gzip -9" > "$DUMP_FILE"
+        ${MYSQL_DATABASE} ${MYSQL_TABLES[*]} | gzip -9" >"$DUMP_FILE"
     ;;
-    -r|--restore)
-      docker exec -i "${COMPOSE_PROJECT_NAME}-db" sh -c \
-        "exec gunzip -c | mysql -u'${MYSQL_USER}' -p'${MYSQL_PASSWORD}' ${MYSQL_DATABASE}" < "$DUMP_FILE"
+  -r | --restore)
+    docker exec -i "${COMPOSE_PROJECT_NAME}-db" sh -c \
+      "exec gunzip -c | mysql -u'${MYSQL_USER}' -p'${MYSQL_PASSWORD}' ${MYSQL_DATABASE}" <"$DUMP_FILE"
     ;;
-    *) printf "error: Not specified(s) required parameter(s)\n%s\n" "$HELP" && exit 1 ;;
+  *) printf "error: Not specified(s) required parameter(s)\n%s\n" "$HELP" && exit 1 ;;
   esac
 fi
diff --git a/bin/symlink b/bin/symlink
--- a/bin/symlink
+++ b/bin/symlink
@@ -14,15 +14,15 @@ if [ "$1" = -h ] || [ "$1" = --help ]; then
 fi
 
 case "$1" in
-  -c|--create)
-    if [ ! -d /var/www ]; then sudo mkdir /var/www; fi
-    PROJECT_DIR="$(readlink --canonicalize "$(dirname "$0")/../html")"
-    $0 -r && cd /var/www &> /dev/null || exit 1 && sudo ln -s "$PROJECT_DIR" html && cd - &> /dev/null || exit 1
+-c | --create)
+  if [ ! -d /var/www ]; then sudo mkdir /var/www; fi
+  PROJECT_DIR="$(readlink --canonicalize "$(dirname "$0")/../html")"
+  $0 -r && cd /var/www &>/dev/null || exit 1 && sudo ln -s "$PROJECT_DIR" html && cd - &>/dev/null || exit 1
   ;;
-  -r|--remove)
-    if [ -h /var/www/html ]; then sudo rm /var/www/html; fi
+-r | --remove)
+  if [ -h /var/www/html ]; then sudo rm /var/www/html; fi
   ;;
-  *)
-    printf "error: Not specified(s) required parameter(s)\n%s\n" "$HELP" && exit 1
+*)
+  printf "error: Not specified(s) required parameter(s)\n%s\n" "$HELP" && exit 1
   ;;
 esac
