Refactor in symlink script

diff --git a/bin/symlink b/bin/symlink
--- a/bin/symlink
+++ b/bin/symlink
@@ -22,6 +22,6 @@ case "$1" in
     if [ -s /var/www ]; then sudo rm /var/www; fi
   ;;
   *)
-    printf "error: Required parameter(s) are not specified\n\n%s\n" "$HELP" && exit 1
+    printf "error: Required parameter(s) are not specified\n%s\n" "$HELP" && exit 1
   ;;
 esac
